package com.footballay.core.infra.persistence.core.repository

import com.footballay.core.infra.persistence.core.entity.FixtureCore
import com.footballay.core.domain.fixture.FixtureStatusCode
import com.footballay.core.infra.persistence.apisports.entity.FixtureApiSports
import com.footballay.core.infra.persistence.apisports.repository.FixtureApiSportsRepository
import com.footballay.core.infra.persistence.core.entity.LeagueCore
import com.footballay.core.infra.persistence.core.entity.LeagueSeasonCore
import com.footballay.core.infra.persistence.core.entity.TeamCore
import com.footballay.core.logger
import jakarta.persistence.EntityManager
import jakarta.persistence.PersistenceContext
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.test.context.ActiveProfiles
import org.springframework.transaction.annotation.Transactional
import java.time.Instant
import java.time.temporal.ChronoUnit

/**
 * FixtureCoreRepository 단위 테스트
 *
 * ## 테스트 목적
 * - 각 Repository 메서드의 쿼리가 올바르게 동작하는지 검증
 * - 비즈니스 로직 조합은 Service 레이어에서 테스트
 *
 * @author Footballay Core Team
 */
@SpringBootTest
@ActiveProfiles("test")
@Transactional
class FixtureCoreRepositoryTest {
    val log = logger()

    @Autowired
    private lateinit var fixtureCoreRepository: FixtureCoreRepository

    @Autowired
    private lateinit var fixtureApiSportsRepository: FixtureApiSportsRepository

    @Autowired
    private lateinit var leagueCoreRepository: LeagueCoreRepository

    @Autowired
    private lateinit var leagueSeasonCoreRepository: LeagueSeasonCoreRepository

    @Autowired
    private lateinit var teamCoreRepository: TeamCoreRepository

    @PersistenceContext
    private lateinit var em: EntityManager

    private lateinit var testLeague: LeagueCore
    private lateinit var homeTeam: TeamCore
    private lateinit var awayTeam: TeamCore
    private val leagueSeasons = mutableMapOf<String, LeagueSeasonCore>()

    @BeforeEach
    fun setUp() {
        leagueSeasons.clear()
        testLeague =
            LeagueCore(
                uid = "test_league_repo",
                name = "Test League Repository",
                available = true,
                autoGenerated = false,
            )
        leagueCoreRepository.save(testLeague)
        leagueSeasons[testLeague.uid] =
            leagueSeasonCoreRepository.save(
                LeagueSeasonCore(
                    league = testLeague,
                    seasonYear = 2025,
                    current = true,
                    autoGenerated = false,
                ),
            )

        homeTeam =
            TeamCore(
                uid = "home_team_repo",
                name = "Home Team Repo",
                autoGenerated = false,
            )
        awayTeam =
            TeamCore(
                uid = "away_team_repo",
                name = "Away Team Repo",
                autoGenerated = false,
            )
        teamCoreRepository.saveAll(listOf(homeTeam, awayTeam))

        em.flush()
        em.clear()
    }

    @Test
    fun `범위 내 fixtures만 조회 - findFixturesInKickoffRange`() {
        // Given
        val start = Instant.parse("2025-03-05T00:00:00Z")
        val end = Instant.parse("2025-03-06T00:00:00Z")

        val fixturesInRange =
            listOf(
                createFixture("in1", start.plus(2, ChronoUnit.HOURS)),
                createFixture("in2", start.plus(12, ChronoUnit.HOURS)),
            )

        val fixtureOutOfRange = createFixture("out", end.plus(1, ChronoUnit.HOURS))

        fixtureCoreRepository.saveAll(fixturesInRange + fixtureOutOfRange)
        em.flush()
        em.clear()

        // When
        val result = fixtureCoreRepository.findFixturesInKickoffRange(testLeague.id!!, start, end)

        // Then
        assertThat(result).hasSize(2)
        assertThat(result.map { it.uid }).containsExactly("in1", "in2")
    }

    @Test
    fun `시간 범위에서 end 는 Exclusive - findFixturesInKickoffRange`() {
        // Given
        val start = Instant.parse("2025-03-05T10:00:00Z")
        val end = Instant.parse("2025-03-05T20:00:00Z") // end Exclusive

        val fixturesIn =
            listOf(
                createFixture("at_start", start), // startInclusive
                createFixture("in_range", start.plus(1, ChronoUnit.HOURS)), // 범위 내
            )
        val fixturesEx =
            listOf(
                createFixture("at_end", end), // endExclusive - 제외되어야 함
            )

        fixtureCoreRepository.saveAll(fixturesIn + fixturesEx)
        em.flush()
        em.clear()

        // When
        val result = fixtureCoreRepository.findFixturesInKickoffRange(testLeague.id!!, start, end)

        // Then
        assertThat(result).hasSize(2)
        assertThat(result.map { it.uid }).containsExactly("at_start", "in_range")
    }

    @Test
    fun `kickoff 오름차순 정렬 - findFixturesInKickoffRange`() {
        // Given
        val start = Instant.parse("2025-03-05T00:00:00Z")
        val end = Instant.parse("2025-03-06T00:00:00Z")

        val fixtures =
            listOf(
                createFixture("f3", start.plus(20, ChronoUnit.HOURS)),
                createFixture("f1", start.plus(5, ChronoUnit.HOURS)),
                createFixture("f2", start.plus(12, ChronoUnit.HOURS)),
            )

        fixtureCoreRepository.saveAll(fixtures)
        em.flush()
        em.clear()

        // When
        val result = fixtureCoreRepository.findFixturesInKickoffRange(testLeague.id!!, start, end)

        // Then
        assertThat(result.map { it.uid }).containsExactly("f1", "f2", "f3")
    }

    @Test
    fun `다른 리그는 제외 - findFixturesInKickoffRange`() {
        // Given
        val otherLeague =
            LeagueCore(
                uid = "other_league",
                name = "Other League",
                available = true,
                autoGenerated = false,
            )
        leagueCoreRepository.save(otherLeague)

        val start = Instant.parse("2025-03-05T00:00:00Z")
        val end = Instant.parse("2025-03-06T00:00:00Z")
        val kickoff = start.plus(10, ChronoUnit.HOURS)

        val testLeagueFixture =
            createFixture("test_league_fixture", kickoff)
        val otherLeagueFixture =
            createFixture(
                "other_league_fixture",
                kickoff,
                league = otherLeague,
            )

        fixtureCoreRepository.saveAll(listOf(testLeagueFixture, otherLeagueFixture))
        em.flush()
        em.clear()

        // When
        val result = fixtureCoreRepository.findFixturesInKickoffRange(testLeague.id!!, start, end)

        // Then
        assertThat(result).hasSize(1)
        assertThat(result[0].uid).isEqualTo("test_league_fixture")
    }

    @Test
    fun `빈 범위면 빈 리스트 반환 - findFixturesInKickoffRange`() {
        // Given
        val start = Instant.parse("2025-03-05T00:00:00Z")
        val end = Instant.parse("2025-03-06T00:00:00Z")

        val pastFixture = createFixture("past", start.minus(10, ChronoUnit.DAYS))
        val futureFixture = createFixture("future", end.plus(10, ChronoUnit.DAYS))

        fixtureCoreRepository.saveAll(listOf(pastFixture, futureFixture))
        em.flush()
        em.clear()

        // When
        val result = fixtureCoreRepository.findFixturesInKickoffRange(testLeague.id!!, start, end)

        // Then
        assertThat(result).isEmpty()
    }

    @Test
    fun `가장 가까운 kickoff 시각 반환 - findMinKickoffAfter`() {
        // Given
        val from = Instant.parse("2025-03-05T10:00:00Z")

        val fixtures =
            listOf(
                createFixture("f1", from.plus(10, ChronoUnit.DAYS)), // 가장 먼 미래
                createFixture("f2", from.plus(2, ChronoUnit.DAYS)), // 가장 가까운 미래
                createFixture("f3", from.plus(5, ChronoUnit.DAYS)),
            )

        fixtureCoreRepository.saveAll(fixtures)
        em.flush()
        em.clear()

        // When
        val result = fixtureCoreRepository.findMinKickoffAfter(testLeague.id!!, from)

        // Then
        assertThat(result).isEqualTo(from.plus(2, ChronoUnit.DAYS))
    }

    @Test
    fun `from과 같은 시각도 포함 (Inclusive) - findMinKickoffAfter`() {
        // Given
        val exactTime = Instant.parse("2025-03-05T15:30:00Z")
        val fixture = createFixture("exact", exactTime)
        fixtureCoreRepository.save(fixture)
        em.flush()
        em.clear()

        // When
        val result = fixtureCoreRepository.findMinKickoffAfter(testLeague.id!!, exactTime)

        // Then
        assertThat(result).isEqualTo(exactTime)
    }

    @Test
    fun `과거 경기는 제외 - findMinKickoffAfter`() {
        // Given
        val from = Instant.parse("2025-03-10T10:00:00Z")

        val fixtures =
            listOf(
                createFixture("past1", from.minus(5, ChronoUnit.DAYS)),
                createFixture("past2", from.minus(1, ChronoUnit.DAYS)),
                createFixture("future", from.plus(1, ChronoUnit.DAYS)),
            )

        fixtureCoreRepository.saveAll(fixtures)
        em.flush()
        em.clear()

        // When
        val result = fixtureCoreRepository.findMinKickoffAfter(testLeague.id!!, from)

        // Then
        assertThat(result).isEqualTo(from.plus(1, ChronoUnit.DAYS))
    }

    @Test
    fun `미래 경기 없으면 null 반환 - findMinKickoffAfter`() {
        // Given
        val from = Instant.parse("2025-03-10T10:00:00Z")
        val pastFixture = createFixture("past", from.minus(5, ChronoUnit.DAYS))

        fixtureCoreRepository.save(pastFixture)
        em.flush()
        em.clear()

        // When
        val result = fixtureCoreRepository.findMinKickoffAfter(testLeague.id!!, from)

        // Then
        assertThat(result).isNull()
    }

    @Test
    fun `다른 리그는 제외 - findMinKickoffAfter`() {
        // Given
        val otherLeague =
            LeagueCore(
                uid = "other_league",
                name = "Other League",
                available = true,
                autoGenerated = false,
            )
        leagueCoreRepository.save(otherLeague)

        val from = Instant.parse("2025-03-05T10:00:00Z")
        val nearDate = from.plus(2, ChronoUnit.DAYS)
        val farDate = from.plus(5, ChronoUnit.DAYS)

        val testLeagueFixture = createFixture("test", farDate)
        val otherLeagueFixture =
            createFixture(
                "other",
                nearDate,
                league = otherLeague,
            )

        fixtureCoreRepository.saveAll(listOf(testLeagueFixture, otherLeagueFixture))
        em.flush()
        em.clear()

        // When
        val result = fixtureCoreRepository.findMinKickoffAfter(testLeague.id!!, from)

        // Then: 다른 리그의 더 가까운 경기는 무시
        assertThat(result).isEqualTo(farDate)
    }

    @Test
    fun `fixture core 는 nullable league season 을 저장할 수 있다`() {
        val leagueSeason = leagueSeasons.getValue(testLeague.uid)
        fixtureCoreRepository.save(
            createFixture(
                uid = "fixture-with-league-season",
                kickoff = Instant.parse("2025-08-01T12:00:00Z"),
                leagueSeason = leagueSeason,
            ),
        )
        fixtureCoreRepository.save(
            createFixture(
                uid = "fixture-without-league-season",
                kickoff = Instant.parse("2025-08-01T13:00:00Z"),
                leagueSeason = null,
            ),
        )
        em.flush()
        em.clear()

        val found = fixtureCoreRepository.findByUid("fixture-with-league-season")

        assertThat(found.leagueSeason).isNotNull
        assertThat(found.leagueSeason?.id).isEqualTo(leagueSeason.id)
        assertThat(found.leagueSeason?.league?.id).isEqualTo(testLeague.id)
        assertThat(fixtureCoreRepository.findByUid("fixture-without-league-season").leagueSeason).isNull()
    }

    @Test
    @DisplayName("리그 날짜 조회 kickoff query는 timezone으로 계산된 시작 자정을 포함하고 종료 자정은 제외한다")
    fun findDistinctDefaultKickoffsByLeagueUidInRangeUsesInclusiveExclusiveInstants() {
        // Asia/Seoul 2025-03-02의 시작과 다음 날 시작을 UTC Instant로 변환한 범위입니다.
        val startInclusive = Instant.parse("2025-03-01T15:00:00Z")
        val endExclusive = Instant.parse("2025-03-02T15:00:00Z")
        createApiSportsBackedFixture("at-seoul-midnight", startInclusive)
        createApiSportsBackedFixture("same-seoul-midnight", startInclusive)
        createApiSportsBackedFixture("inside-range", endExclusive.minus(1, ChronoUnit.SECONDS))
        createApiSportsBackedFixture("at-next-seoul-midnight", endExclusive)
        em.flush()
        em.clear()

        val result =
            fixtureCoreRepository.findDistinctDefaultKickoffsByLeagueUidInRange(
                testLeague.uid,
                startInclusive,
                endExclusive,
            )

        assertThat(result).containsExactlyInAnyOrder(startInclusive, endExclusive.minus(1, ChronoUnit.SECONDS))
    }

    @Test
    @DisplayName("리그 날짜 조회 kickoff query는 다른 리그의 경기를 반환하지 않는다")
    fun findDistinctDefaultKickoffsByLeagueUidInRangeExcludesOtherLeagues() {
        val otherLeague =
            leagueCoreRepository.save(
                LeagueCore(
                    uid = "other-league-for-dates",
                    name = "Other League",
                    available = true,
                    autoGenerated = false,
                ),
            )
        val startInclusive = Instant.parse("2025-03-05T00:00:00Z")
        val endExclusive = Instant.parse("2025-03-06T00:00:00Z")
        val targetLeagueKickoff = Instant.parse("2025-03-05T10:00:00Z")
        createApiSportsBackedFixture("target-league-fixture", targetLeagueKickoff)
        createApiSportsBackedFixture("other-league-fixture", Instant.parse("2025-03-05T11:00:00Z"), otherLeague)
        em.flush()
        em.clear()

        val result =
            fixtureCoreRepository.findDistinctDefaultKickoffsByLeagueUidInRange(
                testLeague.uid,
                startInclusive,
                endExclusive,
            )

        assertThat(result).containsExactly(targetLeagueKickoff)
    }

    @Test
    @DisplayName("리그 날짜 조회 kickoff query는 같은 리그의 과거와 현재 시즌 경기를 모두 반환한다")
    fun findDistinctDefaultKickoffsByLeagueUidInRangeIncludesAllLeagueSeasons() {
        val previousSeason =
            leagueSeasonCoreRepository.save(
                LeagueSeasonCore(
                    league = testLeague,
                    seasonYear = 2024,
                    current = false,
                    autoGenerated = false,
                ),
            )
        val currentSeason = leagueSeasons.getValue(testLeague.uid)
        val startInclusive = Instant.parse("2025-03-05T00:00:00Z")
        val endExclusive = Instant.parse("2025-03-06T00:00:00Z")
        val previousSeasonKickoff = Instant.parse("2025-03-05T10:00:00Z")
        val currentSeasonKickoff = Instant.parse("2025-03-05T12:00:00Z")
        createApiSportsBackedFixture("previous-season-fixture", previousSeasonKickoff, leagueSeason = previousSeason)
        createApiSportsBackedFixture("current-season-fixture", currentSeasonKickoff, leagueSeason = currentSeason)
        em.flush()
        em.clear()

        val result =
            fixtureCoreRepository.findDistinctDefaultKickoffsByLeagueUidInRange(
                testLeague.uid,
                startInclusive,
                endExclusive,
            )

        assertThat(result).containsExactlyInAnyOrder(previousSeasonKickoff, currentSeasonKickoff)
    }

    @Test
    @DisplayName("리그 날짜 조회 kickoff query는 Backbone 연결이 없는 Core fixture도 반환한다")
    fun findDistinctDefaultKickoffsByLeagueUidInRangeIncludesCoreOnlyFixtures() {
        val startInclusive = Instant.parse("2025-03-05T00:00:00Z")
        val endExclusive = Instant.parse("2025-03-06T00:00:00Z")
        val coreOnlyKickoff = Instant.parse("2025-03-05T11:00:00Z")
        fixtureCoreRepository.save(createFixture("core-only-fixture", coreOnlyKickoff))
        em.flush()
        em.clear()

        val result =
            fixtureCoreRepository.findDistinctDefaultKickoffsByLeagueUidInRange(
                testLeague.uid,
                startInclusive,
                endExclusive,
            )

        assertThat(result).containsExactly(coreOnlyKickoff)
    }

    @Test
    @DisplayName("available fixture 조회는 league season 경로로 모든 시즌의 경기만 반환한다")
    fun findAvailableFixturesByLeagueUidIncludesAllSeasons() {
        val previousSeason =
            leagueSeasonCoreRepository.save(
                LeagueSeasonCore(
                    league = testLeague,
                    seasonYear = 2024,
                    current = false,
                    autoGenerated = false,
                ),
            )
        val otherLeague =
            leagueCoreRepository.save(
                LeagueCore(
                    uid = "other-available-league",
                    name = "Other Available League",
                    available = true,
                    autoGenerated = false,
                ),
            )
        fixtureCoreRepository.saveAll(
            listOf(
                createFixture("available-current", Instant.parse("2025-08-01T10:00:00Z")),
                createFixture(
                    "available-previous",
                    Instant.parse("2024-08-01T10:00:00Z"),
                    leagueSeason = previousSeason,
                ),
                createFixture("unavailable-current", Instant.parse("2025-08-02T10:00:00Z"), available = false),
                createFixture("available-other", Instant.parse("2025-08-03T10:00:00Z"), league = otherLeague),
                createFixture(
                    "legacy-league-only",
                    Instant.parse("2025-08-04T10:00:00Z"),
                    leagueSeason = seasonFor(otherLeague),
                ),
            ),
        )
        em.flush()
        em.clear()

        val result = fixtureCoreRepository.findAvailableFixturesByLeagueUid(testLeague.uid)

        assertThat(result.map { it.uid }).containsExactlyInAnyOrder("available-current", "available-previous")
    }

    @Test
    @DisplayName("available fixture 조회는 직접 리그가 같아도 시즌 없는 경기를 제외한다.")
    fun findAvailableFixturesByLeagueUidExcludesFixturesWithoutSeason() {
        fixtureCoreRepository.saveAll(
            listOf(
                createFixture("season-linked", Instant.parse("2025-08-01T10:00:00Z")),
                createFixture("season-missing", Instant.parse("2025-08-02T10:00:00Z"), leagueSeason = null),
            ),
        )
        em.flush()
        em.clear()

        val result = fixtureCoreRepository.findAvailableFixturesByLeagueUid(testLeague.uid)

        assertThat(result.map { it.uid }).containsExactly("season-linked")
    }

    @Test
    @DisplayName("available fixture 리그 조회는 시즌과 경기 수에 관계없이 리그 uid를 한 번만 반환한다")
    fun findDistinctLeagueUidsWithAvailableFixturesReturnsEachLeagueOnce() {
        val previousSeason =
            leagueSeasonCoreRepository.save(
                LeagueSeasonCore(
                    league = testLeague,
                    seasonYear = 2024,
                    current = false,
                    autoGenerated = false,
                ),
            )
        val unavailableLeague =
            leagueCoreRepository.save(
                LeagueCore(
                    uid = "unavailable-fixture-league",
                    name = "Unavailable Fixture League",
                    available = true,
                    autoGenerated = false,
                ),
            )
        fixtureCoreRepository.saveAll(
            listOf(
                createFixture("available-current-1", Instant.parse("2025-08-01T10:00:00Z")),
                createFixture("available-current-2", Instant.parse("2025-08-01T11:00:00Z")),
                createFixture(
                    "available-previous-1",
                    Instant.parse("2024-08-01T10:00:00Z"),
                    leagueSeason = previousSeason,
                ),
                createFixture(
                    "unavailable-other-league",
                    Instant.parse("2025-08-02T10:00:00Z"),
                    league = unavailableLeague,
                    available = false,
                ),
            ),
        )
        em.flush()
        em.clear()

        val result = fixtureCoreRepository.findDistinctLeagueUidsWithAvailableFixtures()

        assertThat(result).containsExactly(testLeague.uid)
    }

    private fun createFixture(
        uid: String,
        kickoff: Instant,
        league: LeagueCore = testLeague,
        leagueSeason: LeagueSeasonCore? = seasonFor(league),
        available: Boolean = true,
    ): FixtureCore =
        FixtureCore(
            uid = uid,
            kickoff = kickoff,
            statusText = "Not Started",
            statusCode = FixtureStatusCode.NS,
            league = league,
            leagueSeason = leagueSeason,
            homeTeam = homeTeam,
            awayTeam = awayTeam,
            goalsHome = 0,
            goalsAway = 0,
            finished = false,
            available = available,
            autoGenerated = false,
        )

    private fun seasonFor(league: LeagueCore): LeagueSeasonCore =
        leagueSeasons.getOrPut(league.uid) {
            leagueSeasonCoreRepository.save(
                LeagueSeasonCore(
                    league = league,
                    seasonYear = 2025,
                    current = true,
                    autoGenerated = false,
                ),
            )
        }

    private fun createApiSportsBackedFixture(
        uid: String,
        kickoff: Instant,
        league: LeagueCore = testLeague,
        leagueSeason: LeagueSeasonCore? = seasonFor(league),
    ) {
        val fixture = fixtureCoreRepository.save(createFixture(uid, kickoff, league, leagueSeason))
        fixtureApiSportsRepository.save(
            FixtureApiSports(
                apiId = uid.hashCode().toLong(),
                core = fixture,
                round = "Round 1",
                season = null,
            ),
        )
    }
}
