package com.footballay.core.infra.persistence.core.repository

import com.footballay.core.domain.fixture.FixtureStatusCode
import com.footballay.core.domain.league.MatchCollect
import com.footballay.core.infra.persistence.core.entity.FixtureCore
import com.footballay.core.infra.persistence.core.entity.LeagueCore
import com.footballay.core.infra.persistence.core.entity.LeagueSeasonCore
import jakarta.persistence.EntityManager
import jakarta.persistence.PersistenceContext
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.DisplayName
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.test.context.ActiveProfiles
import org.springframework.transaction.annotation.Transactional
import java.time.Instant

@SpringBootTest
@ActiveProfiles("test")
@Transactional
class FixtureCoreMatchCollectLiveJobRepositoryTest {
    @Autowired
    private lateinit var leagueCoreRepository: LeagueCoreRepository

    @Autowired
    private lateinit var leagueSeasonCoreRepository: LeagueSeasonCoreRepository

    @Autowired
    private lateinit var fixtureCoreRepository: FixtureCoreRepository

    @PersistenceContext
    private lateinit var em: EntityManager

    @Test
    fun `live job reconcile fixture 조회는 current season의 unavailable fixture만 가져오고 matchCollect 값으로 필터링하지 않는다`() {
        val league =
            leagueCoreRepository.save(
                LeagueCore(
                    uid = "league-live-reconcile",
                    name = "League Live Reconcile",
                    available = true,
                    matchCollect = MatchCollect.NONE,
                    autoGenerated = false,
                ),
            )
        val currentSeason =
            leagueSeasonCoreRepository.save(
                LeagueSeasonCore(
                    league = league,
                    seasonYear = 2026,
                    current = true,
                    autoGenerated = false,
                ),
            )
        val oldSeason =
            leagueSeasonCoreRepository.save(
                LeagueSeasonCore(
                    league = league,
                    seasonYear = 2025,
                    current = false,
                    autoGenerated = false,
                ),
            )
        val currentFixture = saveFixture("fixture-current", league, currentSeason)
        saveFixture("fixture-old", league, oldSeason)
        saveFixture("fixture-available", league, currentSeason, available = true)
        em.flush()
        em.clear()

        val result = fixtureCoreRepository.findMatchCollectLiveJobReconcileFixturesByLeagueUid(league.uid)

        assertThat(result.map { it.uid }).containsExactly(currentFixture.uid)
        assertThat(result.first().leagueSeason?.current).isTrue()
        assertThat(result.first().leagueSeason?.league?.matchCollect).isEqualTo(MatchCollect.NONE)
    }

    @Test
    @DisplayName("match collect state reconcile fixture 조회는 league season 경로에서 current season만 가져온다")
    fun findMatchCollectStateReconcileFixturesByLeagueUidIncludesOnlyCurrentSeason() {
        val league =
            leagueCoreRepository.save(
                LeagueCore(
                    uid = "league-state-reconcile",
                    name = "League State Reconcile",
                    available = true,
                    matchCollect = MatchCollect.FINISHED,
                    autoGenerated = false,
                ),
            )
        val currentSeason =
            leagueSeasonCoreRepository.save(
                LeagueSeasonCore(
                    league = league,
                    seasonYear = 2026,
                    current = true,
                    autoGenerated = false,
                ),
            )
        val oldSeason =
            leagueSeasonCoreRepository.save(
                LeagueSeasonCore(
                    league = league,
                    seasonYear = 2025,
                    current = false,
                    autoGenerated = false,
                ),
            )
        val currentFixture = saveFixture("state-current", league, currentSeason, available = true)
        saveFixture("state-old", league, oldSeason)
        em.flush()
        em.clear()

        val result = fixtureCoreRepository.findMatchCollectStateReconcileFixturesByLeagueUid(league.uid)

        assertThat(result.map { it.uid }).containsExactly(currentFixture.uid)
        assertThat(result.first().leagueSeason?.current).isTrue()
        assertThat(result.first().leagueSeason?.league?.uid).isEqualTo(league.uid)
    }

    private fun saveFixture(
        uid: String,
        league: LeagueCore,
        season: LeagueSeasonCore,
        available: Boolean = false,
    ): FixtureCore =
        fixtureCoreRepository.save(
            FixtureCore(
                uid = uid,
                kickoff = Instant.parse("2026-06-15T09:00:00Z"),
                statusText = FixtureStatusCode.NS.code,
                statusCode = FixtureStatusCode.NS,
                league = league,
                leagueSeason = season,
                homeTeam = null,
                awayTeam = null,
                available = available,
                autoGenerated = false,
            ),
        )
}
