package com.footballay.core.infra.backbone.mock.resource

import com.footballay.core.common.result.DomainResult
import com.footballay.core.infra.persistence.core.entity.LeagueCore
import com.footballay.core.infra.persistence.core.entity.LeagueSeasonCore
import com.footballay.core.infra.persistence.core.repository.FixtureCoreRepository
import com.footballay.core.infra.persistence.core.repository.LeagueCoreRepository
import com.footballay.core.infra.persistence.core.repository.LeagueSeasonCoreRepository
import com.footballay.core.infra.persistence.mockbackbone.entity.MockBackboneLeague
import com.footballay.core.infra.persistence.mockbackbone.repository.MockBackboneLeagueRepository
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith
import org.mockito.Mock
import org.mockito.junit.jupiter.MockitoExtension
import org.mockito.kotlin.*
import java.time.Clock
import java.time.Instant
import java.time.ZoneOffset

/** Mock 기본 시즌 생성과 자식부터 삭제하는 순서를 검증합니다. */
@ExtendWith(MockitoExtension::class)
class MockLeagueServiceTest {
    @Mock private lateinit var leagues: LeagueCoreRepository
    @Mock private lateinit var markers: MockBackboneLeagueRepository
    @Mock private lateinit var seasons: LeagueSeasonCoreRepository
    @Mock private lateinit var fixtures: FixtureCoreRepository

    private val clock = Clock.fixed(Instant.parse("2025-12-31T23:59:59Z"), ZoneOffset.ofHours(9))

    private fun service() = MockLeagueService(
        leagueCoreRepository = leagues, mockLeagueRepository = markers,
        leagueSeasonCoreRepository = seasons, fixtureCoreRepository = fixtures,
        modelMapper = MockBackboneModelMapper(), uidFactory = MockUidFactory(clock), clock = clock,
    )

    @Test
    @DisplayName("UTC 생성 연도의 임시 기본 시즌을 하나 만든다")
    fun createDefaultSeasonUsingUtcCreationYear() {
        whenever(leagues.save(any())).thenAnswer { (it.arguments[0] as LeagueCore).apply { id = 1L } }
        whenever(markers.save(any())).thenAnswer { it.arguments[0] }

        assertThat(service().createLeague(MockLeagueCreateCommand(name = "Mock")))
            .isInstanceOf(DomainResult.Success::class.java)

        verify(seasons).save(check {
            assertThat(it.seasonYear).isEqualTo(2025)
            assertThat(it.current).isTrue()
            assertThat(it.autoGenerated).isFalse()
            assertThat(it.league.id).isEqualTo(1L)
        })
    }

    @Test
    @DisplayName("경기가 남아 있으면 리그와 시즌을 삭제하지 않는다")
    fun rejectDeletionWhileFixturesRemain() {
        val league = LeagueCore(id = 1L, uid = "mock", name = "Mock")
        whenever(markers.findByLeagueCoreUid("mock")).thenReturn(MockBackboneLeague(mockUid = "marker", league = league, createdAt = clock.instant()))
        whenever(fixtures.existsByLeagueSeason_League(league)).thenReturn(true)

        assertThat(service().deleteLeague("mock")).isInstanceOf(DomainResult.Fail::class.java)
        verifyNoInteractions(seasons, leagues)
        verify(markers, never()).delete(any())
    }

    @Test
    @DisplayName("시즌을 삭제한 다음 리그를 삭제한다")
    fun deleteSeasonsBeforeLeague() {
        val league = LeagueCore(id = 1L, uid = "mock", name = "Mock")
        val marker = MockBackboneLeague(mockUid = "marker", league = league, createdAt = clock.instant())
        val season = LeagueSeasonCore(league = league, seasonYear = 2025)
        whenever(markers.findByLeagueCoreUid("mock")).thenReturn(marker)
        whenever(seasons.findAllByLeague(league)).thenReturn(listOf(season))

        assertThat(service().deleteLeague("mock")).isInstanceOf(DomainResult.Success::class.java)

        inOrder(seasons, markers, leagues) {
            verify(seasons).deleteAll(listOf(season))
            verify(seasons).flush()
            verify(markers).delete(marker)
            verify(leagues).delete(league)
        }
    }
}
