package com.footballay.core.infra.core

import com.footballay.core.infra.core.dto.FixtureCoreCreateDto
import com.footballay.core.infra.core.dto.FixtureCoreUpdateDto
import com.footballay.core.infra.persistence.core.entity.FixtureCore
import com.footballay.core.domain.fixture.FixtureStatusCode
import com.footballay.core.infra.persistence.core.repository.FixtureCoreRepository
import com.footballay.core.infra.util.UidGenerator
import com.footballay.core.logger
import jakarta.transaction.Transactional
import org.springframework.stereotype.Service

@Service
class FixtureCoreSyncServiceImpl(
    private val fixtureCoreRepository: FixtureCoreRepository,
    private val uidGenerator: UidGenerator,
) : FixtureCoreSyncService {
    private val log = logger()

    override fun <T> generateUidPairs(requests: List<T>): List<Pair<String, T>> =
        requests.map { request ->
            val uid = uidGenerator.generateUid()
            uid to request
        }

    @Transactional
    override fun createFixtureCores(createPairs: List<Pair<String, FixtureCoreCreateDto>>): Map<String, FixtureCore> {
        if (createPairs.isEmpty()) {
            return emptyMap()
        }

        validateCreateRequests(createPairs)

        val fixtureCores =
            createPairs.map { (uid, createDto) ->
                createFixtureCore(uid, createDto)
            }

        val savedFixtureCores = fixtureCoreRepository.saveAll(fixtureCores)

        return savedFixtureCores.associateBy { it.uid }
    }

    @Transactional
    override fun updateFixtureCores(
        updatePairs: List<Pair<FixtureCore, FixtureCoreUpdateDto>>,
    ): Map<String, FixtureCore> {
        if (updatePairs.isEmpty()) {
            return emptyMap()
        }

        val updatedFixtureCores =
            updatePairs.map { (fixtureCore, updateDto) ->
                updateFixtureCore(fixtureCore, updateDto)
            }

        val savedFixtureCores = fixtureCoreRepository.saveAll(updatedFixtureCores)

        return savedFixtureCores.associateBy { it.uid }
    }

    private fun validateCreateRequests(createPairs: List<Pair<String, FixtureCoreCreateDto>>) {
        createPairs.forEach { (_, dto) ->
            require(dto.leagueCore.id != null && dto.leagueCore.id == dto.leagueSeason.league.id) {
                "Fixture league must match its season league: uid=${dto.uid}"
            }
        }
    }

    private fun createFixtureCore(
        uid: String,
        createDto: FixtureCoreCreateDto,
    ): FixtureCore =
        FixtureCore(
            uid = uid,
            kickoff = createDto.kickoff,
            statusText = createDto.status ?: "Unknown",
            statusCode = createDto.statusShort ?: FixtureStatusCode.NS,
            elapsedMin = createDto.elapsedMin,
            // 구 active 및 롤백 호환 쓰기이며 직접 league 매핑 제거 배포에서 정리합니다.
            league = createDto.leagueSeason.league,
            leagueSeason = createDto.leagueSeason,
            homeTeam = createDto.homeTeam,
            awayTeam = createDto.awayTeam,
            goalsHome = createDto.goalsHome,
            goalsAway = createDto.goalsAway,
            finished = createDto.finished,
            available = createDto.available,
            autoGenerated = createDto.autoGenerated,
        )

    private fun updateFixtureCore(
        fixtureCore: FixtureCore,
        updateDto: FixtureCoreUpdateDto,
    ): FixtureCore {
        fixtureCore.kickoff = updateDto.kickoff
        fixtureCore.statusText = updateDto.status
        fixtureCore.statusCode = updateDto.statusShort
        fixtureCore.elapsedMin = updateDto.elapsedMin
        fixtureCore.leagueSeason = updateDto.leagueSeason
        // 구 버전이 읽는 직접 league 값도 시즌 리그와 일치시킵니다.
        fixtureCore.league = updateDto.leagueSeason.league
        fixtureCore.homeTeam = updateDto.homeTeam
        fixtureCore.awayTeam = updateDto.awayTeam
        fixtureCore.goalsHome = updateDto.goalsHome
        fixtureCore.goalsAway = updateDto.goalsAway
        fixtureCore.finished = updateDto.finished
        updateDto.available?.let { fixtureCore.available = it }

        return fixtureCore
    }
}
