package com.footballay.core.web.admin.fixture.service

import com.footballay.core.infra.persistence.apisports.entity.FixtureApiSports
import com.footballay.core.infra.persistence.apisports.entity.LeagueApiSports
import com.footballay.core.infra.persistence.apisports.repository.FixtureApiSportsRepository
import com.footballay.core.infra.persistence.apisports.repository.LeagueApiSportsRepository
import com.footballay.core.infra.persistence.core.entity.FixtureCore
import com.footballay.core.domain.fixture.FixtureStatusCode
import com.footballay.core.infra.persistence.core.entity.LeagueCore
import com.footballay.core.infra.persistence.core.entity.LeagueSeasonCore
import com.footballay.core.infra.persistence.core.entity.TeamCore
import com.footballay.core.infra.persistence.core.repository.FixtureCoreRepository
import com.footballay.core.infra.persistence.core.repository.LeagueCoreRepository
import com.footballay.core.infra.persistence.core.repository.LeagueSeasonCoreRepository
import com.footballay.core.infra.persistence.core.repository.TeamCoreRepository
import com.footballay.core.logger
import com.footballay.core.web.admin.apisports.service.AdminFixtureQueryWebService
import jakarta.persistence.EntityManager
import jakarta.persistence.PersistenceContext
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.security.test.context.support.WithMockUser
import org.springframework.test.context.ActiveProfiles
import org.springframework.transaction.annotation.Transactional
import java.time.Instant
import java.time.ZoneOffset
import java.time.temporal.ChronoUnit

/**
 * AdminFixtureQueryWebService 통합 테스트
 *
 * ## 테스트 범위
 * - exact 모드: 특정 날짜의 모든 fixtures 조회
 * - nearest 모드: 가장 가까운 날짜의 모든 fixtures 조회
 * - DTO 매핑 및 관계 엔티티 로딩 검증
 *
 * @author Footballay Core Team
 */
@SpringBootTest
@ActiveProfiles("test")
@Transactional
@WithMockUser(roles = ["ADMIN"])
class AdminFixtureQueryWebServiceImplTest {
    val log = logger()

    @Autowired
    private lateinit var adminFixtureQueryWebService: AdminFixtureQueryWebService

    @Autowired
    private lateinit var fixtureCoreRepository: FixtureCoreRepository

    @Autowired
    private lateinit var leagueCoreRepository: LeagueCoreRepository

    @Autowired
    private lateinit var leagueSeasonCoreRepository: LeagueSeasonCoreRepository

    @Autowired
    private lateinit var leagueApiSportsRepository: LeagueApiSportsRepository

    @Autowired
    private lateinit var fixtureApiSportsRepository: FixtureApiSportsRepository

    @Autowired
    private lateinit var teamCoreRepository: TeamCoreRepository

    @Autowired
    private lateinit var teamApiSportsRepository: com.footballay.core.infra.persistence.apisports.repository.TeamApiSportsRepository

    @PersistenceContext
    private lateinit var em: EntityManager

    private lateinit var testLeague: LeagueCore
    private lateinit var testSeason: LeagueSeasonCore
    private lateinit var testLeagueApiSports: LeagueApiSports
    private lateinit var homeTeam: TeamCore
    private lateinit var awayTeam: TeamCore

    @BeforeEach
    fun setUp() {
        // 공통 테스트 데이터 생성
        testLeague =
            LeagueCore(
                uid = "test_league",
                name = "Test League",
                available = true,
                autoGenerated = false,
            )
        leagueCoreRepository.save(testLeague)
        testSeason = leagueSeasonCoreRepository.save(LeagueSeasonCore(league = testLeague, seasonYear = 2025))

        // LeagueApiSports 생성 및 LeagueCore 연결
        testLeagueApiSports =
            LeagueApiSports(
                apiId = 999L, // 테스트용 ApiSports ID
                name = "Test League",
                type = "League",
                leagueCore = testLeague,
            )
        leagueApiSportsRepository.save(testLeagueApiSports)

        homeTeam =
            TeamCore(
                uid = "home_team",
                name = "Home Team",
                autoGenerated = false,
            )
        awayTeam =
            TeamCore(
                uid = "away_team",
                name = "Away Team",
                autoGenerated = false,
            )
        teamCoreRepository.saveAll(listOf(homeTeam, awayTeam))

        // TeamApiSports 생성 (DTO 매핑에 필요)
        val homeTeamApiSports =
            com.footballay.core.infra.persistence.apisports.entity.TeamApiSports(
                apiId = 100L,
                name = "Home Team",
                teamCore = homeTeam,
            )
        val awayTeamApiSports =
            com.footballay.core.infra.persistence.apisports.entity.TeamApiSports(
                apiId = 200L,
                name = "Away Team",
                teamCore = awayTeam,
            )
        teamApiSportsRepository.saveAll(listOf(homeTeamApiSports, awayTeamApiSports))

        em.flush()
        em.clear()
    }

    @Test
    fun `exact 모드 - 해당 날짜의 모든 fixtures 반환`() {
        // Given: 2025-03-05에 3개, 2025-03-06에 2개 경기
        val targetDate = Instant.parse("2025-03-05T10:00:00Z")

        createFixture("f1", targetDate, "Not Started")
        createFixture("f2", targetDate.plus(3, ChronoUnit.HOURS), "Not Started")
        createFixture("f3", targetDate.plus(6, ChronoUnit.HOURS), "Not Started")
        createFixture("f4", targetDate.plus(1, ChronoUnit.DAYS), "Not Started")
        createFixture("f5", targetDate.plus(1, ChronoUnit.DAYS).plus(3, ChronoUnit.HOURS), "Not Started")

        em.flush()
        em.clear()

        // When
        val result = adminFixtureQueryWebService.findFixturesByLeague(testLeagueApiSports.apiId, targetDate, "exact", ZoneOffset.UTC)

        // Then
        assertThat(result).hasSize(3)
        assertThat(result.map { it.uid }).containsExactlyInAnyOrder("f1", "f2", "f3")
        log.info("Exact mode: Found ${result.size} fixtures on target date")
    }

    @Test
    fun `exact 모드 - at이 null이면 서버 현재 시간 기준으로 조회`() {
        // Given: 테스트를 위해 현재 시간 근처에 경기 생성
        val now = Instant.now()
        createFixture("today", now, "Not Started")
        createFixture("tomorrow", now.plus(1, ChronoUnit.DAYS), "Not Started")
        em.flush()
        em.clear()

        // When: at=null (서버 현재 시간)
        val result = adminFixtureQueryWebService.findFixturesByLeague(testLeagueApiSports.apiId, null, "exact", ZoneOffset.UTC)

        // Then: 오늘 날짜의 경기만 반환
        assertThat(result).hasSize(1)
        assertThat(result[0].uid).isEqualTo("today")
        log.info("Exact mode with null 'at': Found ${result.size} fixtures for today")
    }

    @Test
    fun `exact 모드 - 해당 날짜에 경기 없으면 빈 리스트 반환`() {
        // Given: 경기가 없는 날짜
        val targetDate = Instant.parse("2025-03-05T10:00:00Z")
        createFixture("f1", targetDate.plus(7, ChronoUnit.DAYS), "Not Started")
        em.flush()
        em.clear()

        // When
        val result = adminFixtureQueryWebService.findFixturesByLeague(testLeagueApiSports.apiId, targetDate, "exact", ZoneOffset.UTC)

        // Then
        assertThat(result).isEmpty()
        log.info("Exact mode: No fixtures found on target date (expected)")
    }

    @Test
    fun `nearest 모드 - 해당 날짜에 경기 있으면 그날 모든 경기 반환`() {
        // Given: 2025-03-05에 2개 경기
        val targetDate = Instant.parse("2025-03-05T10:00:00Z")

        createFixture("f1", targetDate, "Not Started")
        createFixture("f2", targetDate.plus(5, ChronoUnit.HOURS), "Not Started")
        createFixture("f3", targetDate.plus(3, ChronoUnit.DAYS), "Not Started")
        em.flush()
        em.clear()

        // When
        val result = adminFixtureQueryWebService.findFixturesByLeague(testLeagueApiSports.apiId, targetDate, "nearest", ZoneOffset.UTC)

        // Then
        assertThat(result).hasSize(2)
        assertThat(result.map { it.uid }).containsExactlyInAnyOrder("f1", "f2")
        log.info("Nearest mode (same day): Found ${result.size} fixtures")
    }

    @Test
    fun `nearest 모드 - 해당 날짜에 경기 없으면 가장 가까운 미래 날짜 경기 반환`() {
        // Given: 2025-03-05 요청, 03-07에 경기 있음
        val requestDate = Instant.parse("2025-03-05T10:00:00Z")
        val nearestDate = Instant.parse("2025-03-07T10:00:00Z")

        createFixture("f1", nearestDate, "Not Started")
        createFixture("f2", nearestDate.plus(3, ChronoUnit.HOURS), "Not Started")
        createFixture("f3", nearestDate.plus(5, ChronoUnit.DAYS), "Not Started")
        em.flush()
        em.clear()

        // When
        val result = adminFixtureQueryWebService.findFixturesByLeague(testLeagueApiSports.apiId, requestDate, "nearest", ZoneOffset.UTC)

        // Then: 03-07의 모든 경기만 반환
        assertThat(result).hasSize(2)
        assertThat(result.map { it.uid }).containsExactlyInAnyOrder("f1", "f2")
        log.info("Nearest mode (future date): Found ${result.size} fixtures on nearest date (2025-03-07)")
    }

    @Test
    @DisplayName("관리자 nearest는 Core-only 경기를 건너뛰고 ApiSports 연결 경기의 날짜를 선택한다.")
    fun `nearest admin fixture skips earlier core only fixture`() {
        val requestDate = Instant.parse("2025-03-05T00:00:00Z")
        fixtureCoreRepository.save(
            FixtureCore(
                uid = "core-only",
                kickoff = Instant.parse("2025-03-06T10:00:00Z"),
                statusText = "Not Started",
                statusCode = FixtureStatusCode.NS,
                league = testLeague,
                leagueSeason = testSeason,
                homeTeam = null,
                awayTeam = null,
                autoGenerated = false,
            ),
        )
        createFixture("api-backed", Instant.parse("2025-03-07T10:00:00Z"), "Not Started")
        em.flush()
        em.clear()

        val result = adminFixtureQueryWebService.findFixturesByLeague(testLeagueApiSports.apiId, requestDate, "nearest", ZoneOffset.UTC)

        assertThat(result.map { it.uid }).containsExactly("api-backed")
    }

    @Test
    fun `nearest 모드 - 가장 가까운 날짜도 경기 없으면 빈 리스트 반환`() {
        // Given: 아무 경기도 없음
        val requestDate = Instant.parse("2025-03-05T10:00:00Z")

        // When
        val result = adminFixtureQueryWebService.findFixturesByLeague(testLeagueApiSports.apiId, requestDate, "nearest", ZoneOffset.UTC)

        // Then
        assertThat(result).isEmpty()
        log.info("Nearest mode: No fixtures found (expected)")
    }

    @Test
    fun `invalid 모드 - 빈 리스트 반환`() {
        // Given
        val targetDate = Instant.parse("2025-03-05T10:00:00Z")
        createFixture("f1", targetDate, "Not Started")
        em.flush()
        em.clear()

        // When
        val result = adminFixtureQueryWebService.findFixturesByLeague(testLeagueApiSports.apiId, targetDate, "invalid_mode", ZoneOffset.UTC)

        // Then
        assertThat(result).isEmpty()
        log.info("Invalid mode: Returned empty list (expected)")
    }

    @Test
    fun `DTO 매핑 검증 - 모든 필드가 올바르게 매핑되어야 한다`() {
        // Given
        val targetDate = Instant.parse("2025-03-05T14:30:00Z")

        // em.clear() 이후 detached 상태가 된 엔티티들을 다시 조회해서 영속 상태로 만듦
        val persistedLeague = leagueCoreRepository.findById(testLeague.id!!).get()
        val persistedHomeTeam = teamCoreRepository.findById(homeTeam.id!!).get()
        val persistedAwayTeam = teamCoreRepository.findById(awayTeam.id!!).get()

        val fixture =
            FixtureCore(
                uid = "test_fixture",
                kickoff = targetDate,
                statusText = "First Half",
                statusCode = FixtureStatusCode.FIRST_HALF,
                elapsedMin = 30,
                league = persistedLeague,
                leagueSeason = leagueSeasonCoreRepository.findById(testSeason.id!!).get(),
                homeTeam = persistedHomeTeam,
                awayTeam = persistedAwayTeam,
                goalsHome = 2,
                goalsAway = 1,
                finished = false,
                available = true,
                autoGenerated = false,
            )
        fixtureCoreRepository.save(fixture)

        val fixtureApiSports =
            FixtureApiSports(
                apiId = 1234567L,
                core = fixture,
                round = "Round 1",
                season = null,
            )
        fixtureApiSportsRepository.save(fixtureApiSports)
        em.flush()
        em.clear()

        // When
        val result = adminFixtureQueryWebService.findFixturesByLeague(testLeagueApiSports.apiId, targetDate, "exact", ZoneOffset.UTC)

        // Then
        assertThat(result).hasSize(1)
        val dto = result[0]
        assertThat(dto.uid).isEqualTo("test_fixture")
        assertThat(dto.kickoffAt).isEqualTo(targetDate.toString())
        assertThat(dto.home?.name).isEqualTo("Home Team")
        assertThat(dto.away?.name).isEqualTo("Away Team")
        assertThat(dto.status).isEqualTo("1H")
        assertThat(dto.statusText).isEqualTo("First Half")
        assertThat(dto.available).isTrue()

        log.info("DTO mapping verified: $dto")
    }

    private fun createFixture(
        uid: String,
        kickoff: Instant,
        status: String,
        statusCode: FixtureStatusCode = FixtureStatusCode.NS,
    ): FixtureCore {
        // em.clear() 이후 detached 상태가 된 엔티티들을 다시 조회해서 영속 상태로 만듦
        val persistedLeague = leagueCoreRepository.findById(testLeague.id!!).get()
        val persistedHomeTeam = teamCoreRepository.findById(homeTeam.id!!).get()
        val persistedAwayTeam = teamCoreRepository.findById(awayTeam.id!!).get()

        val fixtureCore =
            FixtureCore(
                uid = uid,
                kickoff = kickoff,
                statusText = status,
                statusCode = statusCode,
                elapsedMin = 30,
                league = persistedLeague,
                leagueSeason = leagueSeasonCoreRepository.findById(testSeason.id!!).get(),
                homeTeam = persistedHomeTeam,
                awayTeam = persistedAwayTeam,
                goalsHome = 0,
                goalsAway = 0,
                finished = false,
                available = true,
                autoGenerated = false,
            )
        fixtureCoreRepository.save(fixtureCore)

        val fixtureApiSports =
            FixtureApiSports(
                apiId = uid.hashCode().toLong().let { if (it < 0) -it else it },
                core = fixtureCore,
                round = "Round 1",
                season = null,
            )
        fixtureApiSportsRepository.save(fixtureApiSports)

        return fixtureCore
    }
}
