package com.footballay.core.infra.backbone.mock.resource

import com.footballay.core.common.result.DomainFail
import com.footballay.core.common.result.DomainResult
import com.footballay.core.domain.fixture.FixtureStatusCode
import com.footballay.core.domain.model.FixtureModel
import com.footballay.core.infra.facade.AvailableFixtureFacade
import com.footballay.core.infra.persistence.core.entity.FixtureCore
import com.footballay.core.infra.persistence.core.entity.LeagueTeamCore
import com.footballay.core.infra.persistence.core.repository.FixtureCoreRepository
import com.footballay.core.infra.persistence.core.repository.LeagueSeasonCoreRepository
import com.footballay.core.infra.persistence.core.repository.LeagueTeamCoreRepository
import com.footballay.core.infra.persistence.mockbackbone.entity.MockBackboneFixture
import com.footballay.core.infra.persistence.mockbackbone.entity.MockBackboneLeague
import com.footballay.core.infra.persistence.mockbackbone.entity.MockBackboneTeam
import com.footballay.core.infra.persistence.mockbackbone.repository.MockBackboneFixtureRepository
import com.footballay.core.infra.persistence.mockbackbone.repository.MockBackboneLeagueRepository
import com.footballay.core.infra.persistence.mockbackbone.repository.MockBackboneTeamRepository
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import java.time.Clock
import java.time.Instant

@Service
class MockFixtureService(
    private val fixtureCoreRepository: FixtureCoreRepository,
    private val leagueSeasonCoreRepository: LeagueSeasonCoreRepository,
    private val leagueTeamCoreRepository: LeagueTeamCoreRepository,
    private val mockLeagueRepository: MockBackboneLeagueRepository,
    private val mockTeamRepository: MockBackboneTeamRepository,
    private val mockFixtureRepository: MockBackboneFixtureRepository,
    private val availableFixtureFacade: AvailableFixtureFacade,
    private val modelMapper: MockBackboneModelMapper,
    private val uidFactory: MockUidFactory,
    @Suppress("SpringJavaInjectionPointsAutowiringInspection")
    private val clock: Clock = Clock.systemUTC(),
) {
    @Transactional
    fun createFixture(command: MockFixtureCreateCommand): DomainResult<FixtureModel, DomainFail> {
        validate(command)?.let { return DomainResult.Fail(it) }

        val mockLeague =
            mockLeagueRepository.findByLeagueCoreUid(command.leagueCoreUid)
                ?: return DomainResult.Fail(DomainFail.NotFound("MOCK_BACKBONE_LEAGUE", command.leagueCoreUid))
        val season = leagueSeasonCoreRepository.findByLeagueAndCurrentTrue(mockLeague.league).singleOrNull()
            ?: return DomainResult.Fail(
                validationFail("MOCK_LEAGUE_SEASON_INVALID", "Mock 리그에는 기본 current 시즌이 하나 필요합니다.", "leagueCoreUid"),
            )
        val mockHomeTeam =
            command.homeTeamCoreUid?.let {
                mockTeamRepository.findByTeamCoreUid(it)
                    ?: return DomainResult.Fail(DomainFail.NotFound("MOCK_BACKBONE_TEAM", it))
            }
        val mockAwayTeam =
            command.awayTeamCoreUid?.let {
                mockTeamRepository.findByTeamCoreUid(it)
                    ?: return DomainResult.Fail(DomainFail.NotFound("MOCK_BACKBONE_TEAM", it))
            }

        mockHomeTeam?.let { ensureLeagueTeam(mockLeague, it) }
        mockAwayTeam?.let { ensureLeagueTeam(mockLeague, it) }

        val fixture =
            fixtureCoreRepository.save(
                FixtureCore(
                    uid = uidFactory.fixtureCoreUid(),
                    kickoff = command.kickoff,
                    statusText = statusText(command.statusCode),
                    statusCode = command.statusCode,
                    elapsedMin = null,
                    league = mockLeague.league,
                    leagueSeason = season,
                    homeTeam = mockHomeTeam?.team,
                    awayTeam = mockAwayTeam?.team,
                    finished = isFinished(command.statusCode),
                    available = command.fixtureAvailable,
                    autoGenerated = false,
                ),
            )
        val mockFixture =
            mockFixtureRepository.save(
                MockBackboneFixture(
                    mockUid = uidFactory.fixtureMockUid(),
                    fixture = fixture,
                    initialStatusCode = command.statusCode,
                    initialKickoff = command.kickoff,
                    scenarioUid = command.scenarioUid,
                    scenarioName = command.scenarioName,
                    createdAt = Instant.now(clock),
                ),
            )

        return DomainResult.Success(toModel(mockFixture))
    }

    @Transactional
    fun deleteFixture(fixtureCoreUid: String): DomainResult<FixtureModel, DomainFail> {
        val mockFixture =
            mockFixtureRepository.findByFixtureCoreUid(fixtureCoreUid)
                ?: return DomainResult.Fail(DomainFail.NotFound("MOCK_BACKBONE_FIXTURE", fixtureCoreUid))
        val result = toModel(mockFixture)
        val fixture = mockFixture.fixture

        if (fixture.available) {
            val availableResult = availableFixtureFacade.removeAvailableFixtureByCoreUid(fixture.uid)
            if (availableResult is DomainResult.Fail) {
                return DomainResult.Fail(availableResult.error)
            }
        }

        mockFixtureRepository.delete(mockFixture)
        fixtureCoreRepository.delete(fixture)

        return DomainResult.Success(result)
    }

    fun toModel(mockFixture: MockBackboneFixture): FixtureModel =
        modelMapper.toFixtureModel(mockFixture.fixture)

    private fun validate(command: MockFixtureCreateCommand): DomainFail.Validation? {
        if (command.homeTeamCoreUid != null && command.homeTeamCoreUid == command.awayTeamCoreUid) {
            return validationFail("TEAMS_MUST_BE_DIFFERENT", "홈팀과 원정팀은 달라야 합니다.", "awayTeamCoreUid")
        }
        if (command.fixtureAvailable) {
            return validationFail(
                "FIXTURE_AVAILABLE_NOT_ALLOWED_ON_CREATE",
                "Mock fixture 생성은 available job 을 직접 만들지 않습니다. 생성 후 core uid available API 를 호출해주세요.",
                "fixtureAvailable",
            )
        }
        return null
    }

    private fun ensureLeagueTeam(
        mockLeague: MockBackboneLeague,
        mockTeam: MockBackboneTeam,
    ) {
        val leagueId = requireNotNull(mockLeague.league.id)
        val teamId = requireNotNull(mockTeam.team.id)
        if (!leagueTeamCoreRepository.existsByLeagueIdAndTeamId(leagueId, teamId)) {
            leagueTeamCoreRepository.save(LeagueTeamCore(league = mockLeague.league, team = mockTeam.team))
        }
    }

    private fun statusText(statusCode: FixtureStatusCode): String =
        when (statusCode) {
            FixtureStatusCode.NS -> "Not Started"
            FixtureStatusCode.TBD -> "Time To Be Defined"
            FixtureStatusCode.FT,
            FixtureStatusCode.AET,
            FixtureStatusCode.PEN,
            -> "Match Finished"
            FixtureStatusCode.CANC -> "Match Cancelled"
            FixtureStatusCode.PST -> "Match Postponed"
            FixtureStatusCode.ABD -> "Match Abandoned"
            FixtureStatusCode.AWD -> "Technical Loss"
            FixtureStatusCode.WO -> "WalkOver"
            else -> statusCode.code
        }

    private fun isFinished(statusCode: FixtureStatusCode): Boolean =
        statusCode == FixtureStatusCode.FT ||
            statusCode == FixtureStatusCode.AET ||
            statusCode == FixtureStatusCode.PEN
}
