package com.footballay.core.infra.backbone.mock.resource

import com.footballay.core.common.result.DomainFail
import com.footballay.core.common.result.DomainResult
import com.footballay.core.domain.model.LeagueModel
import com.footballay.core.infra.persistence.core.entity.LeagueCore
import com.footballay.core.infra.persistence.core.entity.LeagueSeasonCore
import com.footballay.core.infra.persistence.core.repository.LeagueSeasonCoreRepository
import com.footballay.core.infra.persistence.core.repository.FixtureCoreRepository
import com.footballay.core.infra.persistence.core.repository.LeagueCoreRepository
import com.footballay.core.infra.persistence.mockbackbone.entity.MockBackboneLeague
import com.footballay.core.infra.persistence.mockbackbone.repository.MockBackboneLeagueRepository
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import java.time.Clock
import java.time.Instant
import java.time.Year
import java.time.ZoneOffset

@Service
class MockLeagueService(
    private val leagueCoreRepository: LeagueCoreRepository,
    private val mockLeagueRepository: MockBackboneLeagueRepository,
    private val leagueSeasonCoreRepository: LeagueSeasonCoreRepository,
    private val fixtureCoreRepository: FixtureCoreRepository,
    private val modelMapper: MockBackboneModelMapper,
    private val uidFactory: MockUidFactory,
    @Suppress("SpringJavaInjectionPointsAutowiringInspection")
    private val clock: Clock = Clock.systemUTC(),
) {
    @Transactional
    fun createLeague(command: MockLeagueCreateCommand): DomainResult<LeagueModel, DomainFail> {
        if (command.name.isBlank()) {
            return DomainResult.Fail(validationFail("LEAGUE_NAME_BLANK", "리그 이름은 비어 있을 수 없습니다.", "name"))
        }

        val league =
            leagueCoreRepository.save(
                LeagueCore(
                    uid = uidFactory.leagueCoreUid(),
                    name = command.name.trim(),
                    available = command.available,
                    autoGenerated = false,
                ),
            )
        // 임시 생성 정책 ; 생성 시점 연도의 기본 시즌 하나 추가
        leagueSeasonCoreRepository.save(
            LeagueSeasonCore(
                league = league,
                seasonYear = Year.now(clock.withZone(ZoneOffset.UTC)).value,
                current = true,
                autoGenerated = false,
            ),
        )
        val mockLeague =
            mockLeagueRepository.save(
                MockBackboneLeague(
                    mockUid = uidFactory.leagueMockUid(),
                    league = league,
                    scenarioUid = command.scenarioUid,
                    scenarioName = command.scenarioName,
                    createdAt = Instant.now(clock),
                ),
            )

        return DomainResult.Success(toModel(mockLeague))
    }

    @Transactional
    fun deleteLeague(leagueCoreUid: String): DomainResult<LeagueModel, DomainFail> {
        val mockLeague =
            mockLeagueRepository.findByLeagueCoreUid(leagueCoreUid)
                ?: return DomainResult.Fail(DomainFail.NotFound("MOCK_BACKBONE_LEAGUE", leagueCoreUid))
        val result = toModel(mockLeague)

        if (fixtureCoreRepository.existsByLeagueSeason_League(mockLeague.league)) {
            return DomainResult.Fail(validationFail("MOCK_LEAGUE_HAS_FIXTURES", "경기를 먼저 삭제해주세요.", "leagueCoreUid"))
        }

        leagueSeasonCoreRepository.deleteAll(leagueSeasonCoreRepository.findAllByLeague(mockLeague.league))
        leagueSeasonCoreRepository.flush()

        mockLeagueRepository.delete(mockLeague)
        leagueCoreRepository.delete(mockLeague.league)

        return DomainResult.Success(result)
    }

    fun toModel(mockLeague: MockBackboneLeague): LeagueModel =
        modelMapper.toLeagueModel(mockLeague.league)
}
