package com.footballay.core.infra.persistence.read

import com.footballay.core.domain.fixture.FixtureStatusCode
import com.footballay.core.infra.backbone.mock.resource.MockBackboneModelMapper
import com.footballay.core.infra.persistence.apisports.entity.FixtureApiSports
import com.footballay.core.infra.persistence.apisports.entity.LeagueApiSports
import com.footballay.core.infra.persistence.apisports.repository.FixtureApiSportsRepository
import com.footballay.core.infra.persistence.apisports.repository.LeagueApiSportsRepository
import com.footballay.core.infra.persistence.core.entity.FixtureCore
import com.footballay.core.infra.persistence.core.entity.LeagueCore
import com.footballay.core.infra.persistence.core.entity.LeagueSeasonCore
import com.footballay.core.infra.persistence.core.repository.FixtureCoreRepository
import com.footballay.core.infra.persistence.core.repository.LeagueCoreRepository
import com.footballay.core.infra.persistence.core.repository.LeagueSeasonCoreRepository
import com.footballay.core.infra.persistence.mockbackbone.entity.MockBackboneFixture
import com.footballay.core.infra.persistence.mockbackbone.entity.MockBackboneLeague
import com.footballay.core.infra.persistence.mockbackbone.repository.MockBackboneFixtureRepository
import com.footballay.core.infra.persistence.mockbackbone.repository.MockBackboneLeagueRepository
import com.footballay.core.querycapture.SqlCaptureStatementInspector
import com.footballay.core.querycapture.SqlCaptureTestConfiguration
import jakarta.persistence.EntityManager
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.context.annotation.Import
import org.springframework.test.context.ActiveProfiles
import org.springframework.transaction.annotation.Transactional
import java.time.Instant

@SpringBootTest
@ActiveProfiles("test")
@Import(SqlCaptureTestConfiguration::class)
@Transactional
class MockDataReadRepositoryQueryTest {
    @Autowired
    private lateinit var leagueCoreRepository: LeagueCoreRepository

    @Autowired
    private lateinit var fixtureCoreRepository: FixtureCoreRepository

    @Autowired
    private lateinit var leagueSeasonCoreRepository: LeagueSeasonCoreRepository

    @Autowired
    private lateinit var leagueApiSportsRepository: LeagueApiSportsRepository

    @Autowired
    private lateinit var fixtureApiSportsRepository: FixtureApiSportsRepository

    @Autowired
    private lateinit var mockBackboneLeagueRepository: MockBackboneLeagueRepository

    @Autowired
    private lateinit var mockBackboneFixtureRepository: MockBackboneFixtureRepository

    @Autowired
    private lateinit var mockBackboneModelMapper: MockBackboneModelMapper

    @Autowired
    private lateinit var inspector: SqlCaptureStatementInspector

    @Autowired
    private lateinit var entityManager: EntityManager

    private lateinit var apiSportsLeague: LeagueCore
    private lateinit var mockLeague: LeagueCore
    private lateinit var coreOnlyLeague: LeagueCore
    private lateinit var sharedLeague: LeagueCore
    private val leagueSeasons = mutableMapOf<String, LeagueSeasonCore>()

    @BeforeEach
    fun setUp() {
        leagueSeasons.clear()
        apiSportsLeague = saveLeague("api-league", "ApiSports League", available = true)
        mockLeague = saveLeague("mock-league", "Mock League", available = true)
        coreOnlyLeague = saveLeague("core-only-league", "Core Only League", available = true)
        sharedLeague = saveLeague("shared-league", "Shared League", available = true)
        saveLeague("unavailable-mock-league", "Unavailable Mock League", available = false)
            .also(::saveMockBackboneLeague)

        saveApiSportsLeague(apiSportsLeague, 39L)
        saveMockBackboneLeague(mockLeague)
        saveApiSportsLeague(sharedLeague, 140L)
        saveMockBackboneLeague(sharedLeague)

        entityManager.flush()
        entityManager.clear()
    }

    @Test
    fun `mock fixture mapping does not select league per fixture or season`() {
        val previousSeason = leagueSeasonCoreRepository.save(
            LeagueSeasonCore(league = mockLeague, seasonYear = 2025, current = false, autoGenerated = false),
        )
        val kickoff = Instant.parse("2026-06-01T10:00:00Z")
        repeat(4) { index ->
            val fixture = saveFixture("mock-n-plus-one-$index", mockLeague, kickoff.plusSeconds(index.toLong()))
            if (index % 2 == 1) fixture.leagueSeason = previousSeason
            saveMockBackboneFixture(fixture)
        }
        entityManager.flush()
        entityManager.clear()

        inspector.clear()
        val fixtures = mockBackboneFixtureRepository.findMockBackedFixturesByLeagueUidInKickoffRange(
            mockLeague.uid, kickoff, kickoff.plusSeconds(10),
        )
        val selectsAfterQuery = inspector.captured().size
        assertThat(fixtures).hasSize(4)
        assertThat(fixtures.map(mockBackboneModelMapper::toFixtureModel).map { it.leagueUid }).containsOnly(mockLeague.uid)
        assertThat(inspector.captured()).hasSize(selectsAfterQuery)
    }

    @Test
    fun `available league query는 ApiSports-backed와 MockBackbone-backed를 분리한다`() {
        val apiSportsLeagues = leagueCoreRepository.findApiSportsBackedAvailableLeagues()
        val mockLeagues = mockBackboneLeagueRepository.findMockBackedAvailableLeagues()

        assertThat(apiSportsLeagues.map { it.uid }).containsExactlyInAnyOrder("api-league", "shared-league")
        assertThat(mockLeagues.map { it.uid }).containsExactlyInAnyOrder("mock-league", "shared-league")
        assertThat(apiSportsLeagues.map { it.uid }).doesNotContain("core-only-league", "mock-league")
        assertThat(mockLeagues.map { it.uid }).doesNotContain("core-only-league", "api-league", "unavailable-mock-league")
    }

    @Test
    fun `fixture range query는 ApiSports-backed와 MockBackbone-backed를 분리한다`() {
        val start = Instant.parse("2026-06-01T00:00:00Z")
        val end = Instant.parse("2026-06-02T00:00:00Z")
        val apiFixture = saveFixture("api-fixture", apiSportsLeague, Instant.parse("2026-06-01T10:00:00Z"))
        val mockFixture = saveFixture("mock-fixture", mockLeague, Instant.parse("2026-06-01T11:00:00Z"))
        saveFixture("core-only-fixture", coreOnlyLeague, Instant.parse("2026-06-01T12:00:00Z"))
        saveApiSportsFixture(apiFixture)
        saveMockBackboneFixture(mockFixture)

        entityManager.flush()
        entityManager.clear()

        val apiSportsFixtures =
            fixtureCoreRepository.findApiSportsBackedFixturesByLeagueUidInKickoffRange(
                apiSportsLeague.uid,
                start,
                end,
            )
        val mockFixtures =
            mockBackboneFixtureRepository.findMockBackedFixturesByLeagueUidInKickoffRange(
                mockLeague.uid,
                start,
                end,
            )

        assertThat(apiSportsFixtures.map { it.uid }).containsExactly("api-fixture")
        assertThat(mockFixtures.map { it.uid }).containsExactly("mock-fixture")
    }

    @Test
    fun `min max kickoff query는 provider backing별 후보만 사용한다`() {
        val apiFixture = saveFixture("api-kickoff", apiSportsLeague, Instant.parse("2026-06-10T10:00:00Z"))
        val mockFixture = saveFixture("mock-kickoff", mockLeague, Instant.parse("2026-06-05T10:00:00Z"))
        saveFixture("core-only-kickoff", coreOnlyLeague, Instant.parse("2026-06-03T10:00:00Z"))
        saveApiSportsFixture(apiFixture)
        saveMockBackboneFixture(mockFixture)

        entityManager.flush()
        entityManager.clear()

        assertThat(
            fixtureCoreRepository.findMinApiSportsBackedKickoffAfterByLeagueUid(
                apiSportsLeague.uid,
                Instant.parse("2026-06-01T00:00:00Z"),
            ),
        ).isEqualTo(Instant.parse("2026-06-10T10:00:00Z"))
        assertThat(
            fixtureCoreRepository.findMaxApiSportsBackedKickoffBeforeByLeagueUid(
                apiSportsLeague.uid,
                Instant.parse("2026-06-30T00:00:00Z"),
            ),
        ).isEqualTo(Instant.parse("2026-06-10T10:00:00Z"))
        assertThat(
            mockBackboneFixtureRepository.findMinMockBackedKickoffAfterByLeagueUid(
                mockLeague.uid,
                Instant.parse("2026-06-01T00:00:00Z"),
            ),
        ).isEqualTo(Instant.parse("2026-06-05T10:00:00Z"))
        assertThat(
            mockBackboneFixtureRepository.findMaxMockBackedKickoffBeforeByLeagueUid(
                mockLeague.uid,
                Instant.parse("2026-06-30T00:00:00Z"),
            ),
        ).isEqualTo(Instant.parse("2026-06-05T10:00:00Z"))
    }

    @Test
    fun `같은 리그에 여러 backing fixture가 섞여도 range min max query는 provider 범위를 지킨다`() {
        val apiPrevious = saveFixture("shared-api-previous", sharedLeague, Instant.parse("2026-06-01T10:00:00Z"))
        val apiNext = saveFixture("shared-api-next", sharedLeague, Instant.parse("2026-06-03T10:00:00Z"))
        val mockPrevious = saveFixture("shared-mock-previous", sharedLeague, Instant.parse("2026-06-01T20:00:00Z"))
        val mockNext = saveFixture("shared-mock-next", sharedLeague, Instant.parse("2026-06-02T09:00:00Z"))
        saveFixture("shared-core-only-previous", sharedLeague, Instant.parse("2026-06-01T22:00:00Z"))
        saveFixture("shared-core-only-next", sharedLeague, Instant.parse("2026-06-02T12:00:00Z"))
        saveApiSportsFixture(apiPrevious)
        saveApiSportsFixture(apiNext)
        saveMockBackboneFixture(mockPrevious)
        saveMockBackboneFixture(mockNext)

        entityManager.flush()
        entityManager.clear()

        val start = Instant.parse("2026-06-01T00:00:00Z")
        val end = Instant.parse("2026-06-04T00:00:00Z")
        val pivot = Instant.parse("2026-06-02T00:00:00Z")

        val apiSportsFixtures =
            fixtureCoreRepository.findApiSportsBackedFixturesByLeagueUidInKickoffRange(sharedLeague.uid, start, end)
        val mockFixtures =
            mockBackboneFixtureRepository.findMockBackedFixturesByLeagueUidInKickoffRange(sharedLeague.uid, start, end)

        assertThat(apiSportsFixtures.map { it.uid }).containsExactly("shared-api-previous", "shared-api-next")
        assertThat(mockFixtures.map { it.uid }).containsExactly("shared-mock-previous", "shared-mock-next")
        assertThat(fixtureCoreRepository.findMinApiSportsBackedKickoffAfterByLeagueUid(sharedLeague.uid, pivot))
            .isEqualTo(Instant.parse("2026-06-03T10:00:00Z"))
        assertThat(fixtureCoreRepository.findMaxApiSportsBackedKickoffBeforeByLeagueUid(sharedLeague.uid, pivot))
            .isEqualTo(Instant.parse("2026-06-01T10:00:00Z"))
        assertThat(mockBackboneFixtureRepository.findMinMockBackedKickoffAfterByLeagueUid(sharedLeague.uid, pivot))
            .isEqualTo(Instant.parse("2026-06-02T09:00:00Z"))
        assertThat(mockBackboneFixtureRepository.findMaxMockBackedKickoffBeforeByLeagueUid(sharedLeague.uid, pivot))
            .isEqualTo(Instant.parse("2026-06-01T20:00:00Z"))
    }

    @Test
    fun `provider-backed fixture query는 fixture available 여부로 필터링하지 않는다`() {
        val apiFixture =
            saveFixture(
                uid = "unavailable-api-fixture",
                league = sharedLeague,
                kickoff = Instant.parse("2026-06-05T10:00:00Z"),
                available = false,
            )
        val mockFixture =
            saveFixture(
                uid = "unavailable-mock-fixture",
                league = sharedLeague,
                kickoff = Instant.parse("2026-06-05T11:00:00Z"),
                available = false,
            )
        saveApiSportsFixture(apiFixture)
        saveMockBackboneFixture(mockFixture)

        entityManager.flush()
        entityManager.clear()

        val start = Instant.parse("2026-06-05T00:00:00Z")
        val end = Instant.parse("2026-06-06T00:00:00Z")

        val apiSportsFixtures =
            fixtureCoreRepository.findApiSportsBackedFixturesByLeagueUidInKickoffRange(sharedLeague.uid, start, end)
        val mockFixtures =
            mockBackboneFixtureRepository.findMockBackedFixturesByLeagueUidInKickoffRange(sharedLeague.uid, start, end)

        assertThat(apiSportsFixtures.map { it.uid }).containsExactly("unavailable-api-fixture")
        assertThat(mockFixtures.map { it.uid }).containsExactly("unavailable-mock-fixture")
        assertThat(fixtureCoreRepository.findMinApiSportsBackedKickoffAfterByLeagueUid(sharedLeague.uid, start))
            .isEqualTo(Instant.parse("2026-06-05T10:00:00Z"))
        assertThat(mockBackboneFixtureRepository.findMinMockBackedKickoffAfterByLeagueUid(sharedLeague.uid, start))
            .isEqualTo(Instant.parse("2026-06-05T11:00:00Z"))
    }

    @Test
    fun `mock kickoff date query는 범위 경계를 지키고 다른 리그 fixture를 제외한다`() {
        val startInclusive = Instant.parse("2026-06-01T00:00:00Z")
        val endExclusive = Instant.parse("2026-06-02T00:00:00Z")
        val atStart = saveFixture("mock-at-start", mockLeague, startInclusive)
        val beforeEnd = saveFixture("mock-before-end", mockLeague, endExclusive.minusSeconds(1))
        val atEnd = saveFixture("mock-at-end", mockLeague, endExclusive)
        val otherLeagueFixture = saveFixture("mock-other-league", sharedLeague, Instant.parse("2026-06-01T12:00:00Z"))
        saveMockBackboneFixture(atStart)
        saveMockBackboneFixture(beforeEnd)
        saveMockBackboneFixture(atEnd)
        saveMockBackboneFixture(otherLeagueFixture)
        entityManager.flush()
        entityManager.clear()

        val result =
            mockBackboneFixtureRepository.findDistinctMockBackedKickoffsByLeagueUidInRange(
                mockLeague.uid,
                startInclusive,
                endExclusive,
            )

        assertThat(result).containsExactlyInAnyOrder(startInclusive, endExclusive.minusSeconds(1))
    }

    private fun saveApiSportsLeague(
        league: LeagueCore,
        apiId: Long,
    ) {
        leagueApiSportsRepository.save(
            LeagueApiSports(
                apiId = apiId,
                name = league.name,
                leagueCore = league,
                available = true,
            ),
        )
    }

    private fun saveLeague(
        uid: String,
        name: String,
        available: Boolean,
    ): LeagueCore {
        val league =
            leagueCoreRepository.save(
            LeagueCore(
                uid = uid,
                name = name,
                available = available,
                autoGenerated = false,
            ),
        )
        leagueSeasons[uid] =
            leagueSeasonCoreRepository.save(
                LeagueSeasonCore(
                    league = league,
                    seasonYear = 2026,
                    current = true,
                    autoGenerated = false,
                ),
            )
        return league
    }

    private fun saveFixture(
        uid: String,
        league: LeagueCore,
        kickoff: Instant,
        available: Boolean = true,
    ): FixtureCore =
        fixtureCoreRepository.save(
            FixtureCore(
                uid = uid,
                kickoff = kickoff,
                statusText = "Not Started",
                statusCode = FixtureStatusCode.NS,
                league = league,
                leagueSeason = requireNotNull(leagueSeasons[league.uid]),
                homeTeam = null,
                awayTeam = null,
                finished = false,
                available = available,
                autoGenerated = false,
            ),
        )

    private fun saveApiSportsFixture(fixture: FixtureCore) {
        fixtureApiSportsRepository.save(
            FixtureApiSports(
                apiId = requireNotNull(fixture.uid.hashCode().toLong().let { if (it < 0) -it else it }),
                core = fixture,
                round = "Round 1",
                season = null,
            ),
        )
    }

    private fun saveMockBackboneLeague(league: LeagueCore) {
        mockBackboneLeagueRepository.save(
            MockBackboneLeague(
                mockUid = "mock-league-${league.uid}",
                league = league,
                createdAt = Instant.parse("2026-06-01T00:00:00Z"),
            ),
        )
    }

    private fun saveMockBackboneFixture(fixture: FixtureCore) {
        mockBackboneFixtureRepository.save(
            MockBackboneFixture(
                mockUid = "mock-fixture-${fixture.uid}",
                fixture = fixture,
                initialStatusCode = fixture.statusCode,
                initialKickoff = fixture.kickoff,
                createdAt = Instant.parse("2026-06-01T00:00:00Z"),
            ),
        )
    }
}
